language: node_js
node_js:
- '9'
before_install:
- cd massage-booking-system-frontend
- npm install
- CI=false npm run build
install:
- mv build ../massage-booking-system-backend
- cd ../massage-booking-system-backend
- npm install
deploy:
  provider: heroku
  api_key:
    secure: oepfnxHyNeDDJad8T6TN0wZwpbusq94CKdYC9Y6G2or7oS1v57o+dgutwrygd6OPqa2lJVWihJ3MK5WBFT5IFAw+GZiAQXtQs6gYaW1UyfrxaFQwbcMtmCMY59T8rYj+rxPpEcwZqQQ6ik0TV3isdafHnBl8KAL6+XoS6uozbxdj6Z61fPcqkvX14ufS7qV3nCTqBMKhAckiH99ho0Epywd9aGFjhfdivOXIiinzi2E0VgpQvuTDuNfU6xC+3DteCWz1qLOOqL60NK0VxQ2D72dbhaeWb6kpaB0TK7hs/6TUEFbca6pmCG3XBPuX840rWmraUFMxMa9UnE7OhozNrSXmS8tRiaZiChiAJpA5IajywnyDQhMisEfIFLZ9owcZI3PKoLYyFUsp4Zir3E+rZaIiop0XSA2odhooX6C5dYH6PjC5JXNovBp0GimSpzf4t5ZxsIScMKxvvT9NB4HxdAYMo3I9J5EdTnet5hkkwqQ8Tjz49VPXv72h4VM5erc8/PQ0LAkG+rkn84I7lHxX7H7ZrV0fv+j3KTvUK5oE/q55gZkRZNLF+HWOutdfa6/ceBLtKUhEpiRH78ASSLm4w3M3No07zTsubgJ5Mdc1iEkN2N865j8jNMMmqStnu5OWuYB98x/ZPt+k130H4O1L3X/7lRCrNndCn3cq226Zf8g=
  skip_cleanup: true
  app: glacial-lowlands-81447
  on:
    repo: karoliinaemilia/massage-booking-system
